brew "awscli"
brew "bash"
brew "bash-completion"
brew "bat"
brew "bitwarden-cli"
brew "borkdude/brew/babashka"
brew "coreutils"
brew "direnv"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "gnupg"
brew "jq"
brew "lsd"
brew "mise"
brew "pgcli"
brew "pinentry-mac"
brew "pipx"
brew "ripgrep"
brew "stow"
brew "terraform"
brew "the_silver_searcher"
brew "tldr"
brew "tree"
brew "wget"
brew "wxwidgets"

# Yabai
brew "koekeishiya/formulae/yabai"
brew "koekeishiya/formulae/skhd"

# ffmpeg bundle
brew "pandoc"
brew "rga"
brew "poppler"
brew "ffmpeg"

## Emacs & Dependencies
tap "d12frosted/emacs-plus"
brew "emacs-plus@29"

brew "ispell"
brew "aspell"
brew "wakatime-cli"

# Cask Apps
# cask "slack"
# cask "zoom"
cask "appcleaner"
cask "arc"
cask "beekeeper-studio"
cask "bitwarden"
cask "docker"
cask "dropbox"
cask "easydict"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-iosevka"
cask "ghostty"
cask "height"
cask "iterm2"
cask "itsycal"
cask "jordanbaird-ice"
cask "latest"
cask "obs"
cask "raycast"
cask "rescuetime"
cask "rocket"
cask "shottr"
cask "spotify"
cask "todoist"
