tap "fforster/gitlab-mcp", "https://gitlab.com/fforster/homebrew-gitlab-mcp.git"

brew "libpq"
brew "gitlab-mcp"

cask "notion"
cask "loom"
cask "postman"
cask "dbeaver-community"
cask "cursor"
cask "stats"
